spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: '1000'
        format_sql: 'false'
        show_sql: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://3.34.130.154:3306/mysql?useUnicode=true&characterEncoding=UTF-8

  sql:
    init:
      schema-locations: classpath:data.sql
      mode: never






